github.com:
    git_protocol: https
    users:
        Bruno0416:
            oauth_token: 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
    user: Bruno0416
    oauth_token: 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
